### ISSUE TITLE
Error in the Showthread page

### ISSUE THREAD

**Issue by nollidnosnhoj** [Sama34/Additional-Settings-For-Custom-Profile-Fields#1]
http://i.imgur.com/00R8vMX.png

This happened right after I installed and activated the plugin.

Also, when trying to edit the custom profile field, it said that a file was missing in inc/languages/english/admin.... but I assumed that the file was in the inc/languages/english was supposed to be in the directory first mentioned.

**Comment by Sama34** [comment]
That should do it. The language file must be inside the /english/ directory and not the /admin/ one.
